### PR TITLE
purple chickin

### PR DESCRIPTION
**Pull request by mhigley**
Hello Haley. Please consider my image to be added into the project. 💯

### CODE REVIEW

**Comment by HaleyLiaraBennett** [comment]
ouwrvb

**Comment by HaleyLiaraBennett** [comment]
We are Fighting Dreamers seeking for high dream

Fighting Dreamers Don't care how we behave

Fighting Dreamers As you believe in

Oli Oli Oli Oh-! Just go my way!

**Comment by mhigley** [comment]
Thx!

**Comment by HaleyLiaraBennett** [comment]
sureeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Pull request merged**
